name: CI-CD-gitops-pipeline 


on:
  push:
    branches: [Main]
  workflow_dispatch:


env:
  IMAGE_NAME: piyush63/yourapp


jobs:
  build-test:
    runs-on: ubuntu-latest


    steps:
      - name: checkout code and python app pytest
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with { python-version: '3.10'}
      - run: |
          pip install -r requirements.txt
          pip install flake8 && flake8 . || true
          pip install pytest || true && pytest || true

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
      - run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV


  update-manifest:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: checkout manifest repo
      - uses: actions/checkout@v4
        with:
          repository: piyushpy63/manifests-repo
          token: ${{ secrets.GIT_TOKEN }}
          path: manifests
      - name: update deployment image tag
        run: |
          cd manifests
          sed -i "s|image: .*|image: ${IMAGE_NAME}:${IMAGE_TAG}|g" deployment.yaml
      - name: commit and push
        run: |
          cd manifests
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add deployment.yaml
          git commit -m "chore: update image to ${IMAGE_TAG}" || echo "no changes to commit"
          git push






